#!/usr/bin/env bash
# Update package lists

sudo apt-get update

# Install nginx
sudo apt-get -y install nginx

# Ensure nginx is listening on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Create a default HTML page with "Hello World!"
echo "<!DOCTYPE html><html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html

