#!/usr/bin/env bash

nginx_conf="/etc/nginx/sites-enabled/default"

if ! command -v nginx &> /dev/null; then
    exit 1
fi

if ! systemctl is-active --quiet nginx; then
    sudo systemctl start nginx
fi

sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' $nginx_conf
sudo systemctl restart nginx
